name: Android Release Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_DIRECTORY: out
  BUILD_TYPE: release
  BUILD_PLATFORM: android


permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x64, x86]
    steps:
      - uses: actions/checkout@v4
        with:  
          submodules: true

      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.29.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '17'
    
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          ndk-version: '26.1.10909125'
          cmake-version: '3.29.0'

      - name: Build Application
        run: |
            sudo apt-get update -y
            sudo apt-get install -y cmake
            cd ./android
            chmod +x ./gradlew
            ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wipsy-${{env.BUILD_PLATFORM}}-${{matrix.arch}}
          path: ./${{env.BUILD_DIRECTORY}}/android/app/build/outputs/apk/release/app-release.apk

