name: Android Release Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_PATH: ./android/app/build/outputs/apk/release
  BUILD_TYPE: release
  BUILD_PLATFORM: android

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x64, x86]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          distribution: "adopt"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Application
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cmake
          cd ./android
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - uses: ilharp/sign-android-release@v1
        name: Sign APK
        id: signapp
        with:
          releaseDir: ${{env.BUILD_PATH }}
          signingKey: ${{ secrets.SIGNING_KEY_B64 }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename APK
        run: |
          mv ${{steps.signapp.outputs.signedFile}} ${{env.BUILD_PATH }}/wipsy-${{env.BUILD_PLATFORM}}-${{matrix.arch}}.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wipsy-${{env.BUILD_PLATFORM}}-${{matrix.arch}}
          path: ${{env.BUILD_PATH }}/wipsy-${{env.BUILD_PLATFORM}}-${{matrix.arch}}.apk
