name: Build Release x64
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  SOLUTION_FILE_PATH: wispy-c.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Vcpkg
        uses: lukka/run-vcpkg@v11.1
        with:
          vcpkgGitCommitId: 3265c187c74914aa5569b75355badebfdbab7987
          vcpkgJsonGlob: "**/.github/vcpkg.json"

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
