name: Release Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  SOLUTION_FILE_PATH: wispy-c.sln
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            vcpkgPackages: "zlib:x64-windows-static raylib:x64-windows-static"
    steps:
      - uses: actions/checkout@v3

      - name: Vcpkg
        uses: lukka/run-vcpkg@v11.1
        with:
          vcpkgGitCommitId: 3265c187c74914aa5569b75355badebfdbab7987

      - name: Integrate vcpkg
        run: vcpkg integrate install

      - name: Install Packages
        run: vcpkg install ${{ matrix.vcpkgPackages }}

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wipsy-exe
          path: ${{env.GITHUB_WORKSPACE}}/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}/wispy-c.exe
