name: Release Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_DIRECTORY: out
  BUILD_ARCH: x64
  BUILD_TYPE: release
  BUILD_PLATFORM: windows

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest

      # - name: Initialize CodeQL
      #   uses: github/codeql-action/init@v3
      #   with:
      #     languages: "c"

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: ${{env.BUILD_ARCH}}-${{env.BUILD_TYPE}}-${{env.BUILD_PLATFORM}}
          buildPreset: ${{env.BUILD_ARCH}}-${{env.BUILD_TYPE}}-${{env.BUILD_PLATFORM}}
          buildPresetAdditionalArgs: "['--config release']"

      # - name: Perform CodeQL Analysis
      #   uses: github/codeql-action/analyze@v3

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.BUILD_ARCH}}-${{env.BUILD_TYPE}}-${{env.BUILD_PLATFORM}}-wipsy
          path: ./${{env.BUILD_DIRECTORY}}/${{env.BUILD_ARCH}}-${{env.BUILD_TYPE}}-${{env.BUILD_PLATFORM}}/wispy.exe
