name: Release Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  SOLUTION_FILE_PATH: wispy-c.sln
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 360
    permissions:
      security-events: write
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            vcpkgPackages: "zlib:x64-windows-static raylib:x64-windows-static"
    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: "c"

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup Vcpkg
        uses: lukka/run-vcpkg@v11.1
        with:
          vcpkgGitCommitId: 3265c187c74914aa5569b75355badebfdbab7987

      - name: Integrate vcpkg
        run: vcpkg integrate install

      - name: Install Packages
        run: vcpkg install ${{ matrix.vcpkgPackages }}

      - name: Build Solution
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-wipsy
          path: ./${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}/wispy.exe
